<?php

namespace ArticleBundle\Repository;
use ArticleBundle\Entity\Mangas;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MangasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MangasRepository extends \Doctrine\ORM\EntityRepository
{

}
